services:
  agent:
    image: ghcr.io/herol3oy/kiosk24-agent:latest
    pull_policy: always
    container_name: kiosk24-agent
    restart: "no"
    env_file:
      - apps/agent/.env
    environment:
      - NODE_ENV=production